### ISSUE TITLE
Structure of this repo?

### ISSUE THREAD

**Issue by wolandscat** [openEHR/specifications-ITS-REST#1]
I think the structure of this repo should follow the target ITS formalisms, not the abstract components (RM, AM etc). So far I think we have:
- XSD
- BMM
- WSDL
- REST

At the moment, Antlr is considered a specification level formalism, although it is a directly usable technology as well.

**Comment by ppazos** [comment]
+1 for me, please create the folder structure and send a PR @wolandscat 

we can move the apiary file to the REST folder

**Comment by bostjanl** [comment]
I could not get apiary binding to work if the file was not at the root of the repo. I suggest we keep it here for the moment and move once we finalise it - we might also convert to another format at that stage so using apiary might not be so useful anymore.

**Comment by ppazos** [comment]
We discussed some items related to versioning in Slack, some of the management requirements we might need to consider that can be handled by GitHub:

1. ITS artifacts should be linked to spec artifacts.

- can be done via documentation on GH releases, GH Wiki, openEHR spec pages, and openEHR Wiki


2. ITS artifacts will be maintained/modified/released in a more frequent manner than specs, more like code. Users of ITS artifacts need to know which version of each artifact they are using, and easily check for new version release, track issues and fixes.

- major versions of ITS artifacts can be managed in GH branches
- minor versions / revisions can be managed in GH releases (a release creates a tag)
- diffs between releases can be easily done (e.g. https://github.com/ppazos/cabolabs-ehrserver/compare/v0.9.5...v1.0)
- releases can be easily tracked by subscribing to the release feed (e.g. https://github.com/ppazos/cabolabs-ehrserver/releases.atom)
- users might stuck with a specific version of ITS and follow that specific branch for a while, until they update to a new version of the specs, then they will track master or another branch (implementations tend to be stuck on a spec version for some time before upgrading, they will start with a trunk version, but after some releases of the specs, implementation might stay behind spec and ITS trunk)


3. Considering 1. and 2., major versions of ITS artifacts can be mapped to versions of the spec releases.

- might help to have a reference by structure in combination of reference by documentation, but this is micro-optimization.
- any user of ITS artifacts can find exactly what version of the artifact they are using (they will download a version or clone master), and by it's release notes can find to which spec version that ITS is using.
- if master is cloned, there are no release notes, so trunk should have the current spec version it is implementing on the standard README of a GH project, there can be one for the project and one README per subfolder / ITS artifact type.


4. GH milestones can be used to group issues that should be solved for specific branches, and can be used as the baseline to know when to do a release.

- example: https://github.com/ppazos/cabolabs-ehrserver/milestones


Just put the links to things I use in GH as examples, I use it to manage all my projects :)

**Comment by sebastian-iancu** [comment]
The former ITS repo was changed by splitting it to smaller dedicated ones - new resulting repos are now available and linked back as submodules in the new specifications-ITS repo.
This repo is now dedicated to REST only.
