### ISSUE TITLE
Agree on content type for XML requests and responses for v0.1

### ISSUE THREAD

**Issue by ppazos** [openEHR/specifications-ITS-REST#3]
We talk about focusing on XML for a first draft version of the API specs.
1. Just want to double check if we all agree on this, please +1 if you agree.
2. Little discussion about which content type to use for requests and responses. We have text/xml and application/xml, here is some nice info about this: http://stackoverflow.com/questions/4832357/whats-the-difference-between-text-xml-vs-application-xml-for-webservice-respons

Please state which option you prefer and why for point 2.

**Comment by bostjanl** [comment]
We need both JSON and XML already for draft version.

**Comment by ppazos** [comment]
@bostjanl on the meeting we talked about agreeing on an XML because is easier to define a schema, and have a transformation to JSON when the XML schema was established.

I think that is a good approach, because we don't need to define 2 schemas.

I agree we need both on the final spec, just need to agree on a first subset of the spec for v0.1 and I think that should be XML only.

**Comment by bostjanl** [comment]
@ppazos I didn't understand the discussion this way. I think we can define some xml schemas but JSON models might not be 100% the same - they might be very ugly when generated from XML.

**Comment by sebastian-iancu** [comment]
from my point of view JSON is very important, but if we need to be very strict and formal, and time is an issue, I'm also ok if we start only with XML

**Comment by ppazos** [comment]
@bostjanl let's wait for other's opinions. I liked the "XML first" approach to allow formalization from the beginning. Also, having schemas to validate instances is priceless.

I think XML-JSON transformation is a separate discussion, and depends on the tool. I've been using a nice library to transform canonical openEHR XML info JSON, and the results are impressive, also allows JSON to XML. I can create another issue to discuss that and add examples.

**Comment by ErikSundvall** [comment]
Regarding question 1 in this issue: I wrote some related things in issue #6.

Regarding question 2 in this issue: I believe application/xml is suitable for openEHR JSON structures. 
In LiU-EEE we provided many kinds of content types. Supplying fairly RESTful actionable html for debug/developer purposes was useful by the way, see for example Figure 5 in http://bmcmedinformdecismak.biomedcentral.com/articles/10.1186/1472-6947-13-57

(Perhaps we should keep fairly unrelated questions in separate issues,)

**Comment by ppazos** [comment]
@ErikSundvall "I believe application/xml is suitable for openEHR JSON structures." I think you are referring to application/json, not to application/xml.

What I wanted to raise with the second point is that both text/xml and application/xml are valid XML mime types. Also there are subtypes by application, see https://en.wikipedia.org/wiki/XML_and_MIME

We need to choose one of the first two, or define a new one like application/openehr+xml and register it at IANA (http://www.iana.org/assignments/media-types/media-types.xhtml).

**Comment by ErikSundvall** [comment]
Sorry, I didn't type what I was thinking, it should be "I believe application/xml is suitable for openEHR **XML** structures" - at least for the rather unreadable verbose canonical format.

For JSON we should of course use the official application/json
