### ISSUE TITLE
Create official spec for a FLAT (JSON) format 

### ISSUE THREAD

**Issue by ErikSundvall** [openEHR/specifications-ITS-REST#56]
There are several non standardized implementations of "flat" openEHR RM JSON formats, that usually consist of lists of key-value pairs where the key is some kind of path. There are use-cases behind the creation of such formats and it would be good to provide a public specification of such a format.

Two of the flat formats are described at: https://github.com/ethercis/ethercis/blob/master/doc/flat%20json.md

(Please edit this issue ticket to add links to other flat-format descriptions if you know of any)
Background motivation of the need of tracking these thoughts as an official issue: https://github.com/ethercis/ethercis/issues/74#issuecomment-371359396

**Comment by ErikSundvall** [comment]
Discussion starter: Personally I see most value in some natural-language-independent, AQL-path-based version along the lines of ECISFLAT described in https://github.com/ethercis/ethercis/blob/master/doc/flat%20json.md that could be used for cut&paste of paths from tools.

If we want compact language-specific, human-readable serialization, then perhaps it would be higher priority to comple an official spec on TDS3 that is partially described at https://openehr.atlassian.net/wiki/spaces/spec/pages/30408770/Template+Data+Schema+TDS+Specification+and+associated+Template+Data+Document+TDD (maybe a JSON version of it could be derived/specified too)

**Comment by ErikSundvall** [comment]
When 1.0 of the rest spec is done, the "flat JSON format" discussion should be picked up again for version 1.1 of the REST epsc. Some updates/revisions to the discussion starter above follow:

- Language independence is likely not possible when there are otherwise identical sibling nodes.
- Two versions of a flat format might actually be a good thing for different use cases
-- Full flat - showing the as canonical paths as possible, including archetype ID's and at-codes where appropriate. Inspiration: ECISFLAT.
-- Compact flat - does it need to be dependent on some future standardized form definition or is it enough to know the template to maek it compact? Inspiration Marand's flat format
- Calls can likely be unmodified just new content types (and formal format specifications) added
- TDS3/TDD is likely a different use case (and XML centric) that should not be mixed with this Github issue.

**Comment by sebastian-iancu** [comment]
This is taken care in abstract SM, in https://openehr.atlassian.net/browse/SPECITS-33 and https://github.com/openEHR/simplified-format-incubator
